### ISSUE TITLE
Illegal instruction

### ISSUE THREAD

**Issue by Deannord** [sonicretro/s1disasm#14]
I think my SonED2 broke my game,or XVI32,when in the game im reach an trigger to boss fight,it make's to appear an illegal instruction,please tell to how fix it.

**Comment by FraGag** [comment]
Try applying this guide to your disassembly: [SCHG How-to:Fix a race condition with Pattern Load Cues](http://info.sonicretro.org/SCHG_How-to:Fix_a_race_condition_with_Pattern_Load_Cues). When you reach a boss fight, some patterns are loaded in VRAM using a PLC, which can trigger a crash, especially if the game is lagging because it has too much to process in a single frame.

**Comment by Deannord** [comment]
Which programm is need?

11 февр. 2018 г. 14:46 пользователь "Francis Gagné" <
notifications@github.com> написал:

**Comment by Deannord** [comment]
Which programm is need?

**Comment by Techokami** [comment]
You need a text editor. You have to edit the assembly code.

**Comment by Clownacy** [comment]
This isn't a problem with the disassembly, so I'm closing this.
