### ISSUE TITLE
(AS branch) Are pre-compiled build tools a good idea?

### ISSUE THREAD

**Issue by Clownacy** [sonicretro/s1disasm#24]
I can understand this for Windows and possibly Mac OS, but isn't distributing binaries a bad idea for Linux? I mean, we'll never provide up-to-date binaries for every platform out there, but a system like s2disasm's (where the build script compiles the tools on its first run) would support just about anything with GCC on it.

**Comment by FraGag** [comment]
I think many Linux distributions don't install GCC by default. GCC (g++, actually, because our tools are written in C++) is a rather large package to install when you consider all dependencies, so it can be annoying to download and install a compiler just to build a couple of tools.

I'm not sure I get what you mean by "we'll never provide up-to-date binaries for every platform out there". First, I think the objective is to cover the most common platforms, and second, if updating the tools is too troublesome, then perhaps we could set up some CI to update the tools automatically (in that case, it might be better to put the binaries on the Releases page rather than in the repo itself).

**Comment by Clownacy** [comment]
```
I'm not sure I get what you mean by "we'll never provide up-to-date binaries for every platform out there". First, I think the objective is to cover the most common platforms
```
Raspberry Pis are pretty common, especially among programmers who probably have a GCC installation at hand, yet we don't provide ARM binaries.

Not needing to install a dependency or two is nice and all, but my point is isn't cross-distro binary compatibility really spotty?

Putting the tools in the Releases page sounds like needless fragmentation. The tools don't change that often.

**Comment by Clownacy** [comment]
Bleh. Having rewritten the build scripts of both this and the Sonic 2 disassembly, I now think that the best way to avoid pre-built binaries is to just not use compiled languages at all, and instead replace them with interpreted languages. Still, there's no avoiding the need for binaries of the assembler itself, so I guess binaries will always be a necessary evil to some degree. Closing.
