### ISSUE TITLE
The "music" and "sfx" macros and "OptimiseSound"

### ISSUE THREAD

**Issue by ghost** [sonicretro/s1disasm#47]
Honestly, these 2 macros and optimization option are useless. The macros are overly convoluted and considering "OptimiseSound" is the only optimization option in the entire disassembly as far as I can see, what's the point? It's not like changing all the PlaySound branches to be direct writes would save many cycles considering that they are only called a few times in a single frame. Also, the "music" and "sfx" names are pretty much misnomers, since the sound queues aren't limited to a particular sound type (See loc_47D4 and LevSel_Credits, for instance).

**Comment by Clownacy** [comment]
Just to weigh-in - I'm partly responsible for those macros being as awful as they are (see c2697322bb46b9962b272a18c1d41ed5d11b813b). I never liked those macros, and only contributed to them because I figured removing them wasn't an option.

I dislike how they obfuscate the functionality of the underlying code (hiding an implicit `rts` is probably the worst part), and I think it's pretty clear that the original source code didn't use macros for that kind of thing, making them an extremely poor fit:

The current implementation of these macros has a series of boolean arguments with no obvious meaning at a first glance, which control the instructions used to set the register and call the function. Had the original source code used macros, chances are these instructions would be uniform - not massively inconsistent like they are in the built ROM.
