### ISSUE TITLE
VirusTotal detects “BehavesLike.Sality.tc” on the disassembly!

### ISSUE THREAD

**Issue by hexxer666** [sonicretro/s1disasm#50]
![A1A433BF-9FB8-4F51-846C-6F7781711E77](https://user-images.githubusercontent.com/72986491/96275593-89203600-0f97-11eb-8d16-d3c7bfb47a4d.jpeg) I recently scanned the disassembly through **VirusTotal**, and one of the antivirus engines detected that it contains **“BehavesLike.Sality.tc”**. Is that a false positive?

**Comment by NatsumiFox** [comment]
There are a lot of false positives with virus scanners, and because they really aren't designed to deal with rare cases like ROM hacking and programming (afterall, most people who use virus scanners are browsing facebook and downloading stuff from suspicious sites), its more than likely if its some kind of generic malware then it's always a false positive. Not always but I would bet on it if it's from a reputable source that hundreds of technically minded people already use

**Comment by flamewing** [comment]
Also, a single engine out of 59 made that alleged detection. The likelihood of something being a false positive is inversely proportional to the proportion of engines that detect said thing.
