### ISSUE TITLE
How do i make it so it applys to an already-edited rom?

### ISSUE THREAD

**Issue by PDL2CGamejolt** [sonicretro/s1disasm#59]
I am making a rom and i already edited it before i tried this

**Comment by Clownacy** [comment]
It's not really possible anymore: old (and I mean [_very_ old](http://info.sonicretro.org/File:Sonic_1_(Split_and_Text_by_Hivebrain)_(ASM68K).zip)) versions of this disassembly used to include a splitter tool that would extract data from a pre-existing ROM, but the disassembly has probably changed so much since then that the extracted files wouldn't have the right names anymore.

You can find a copy of the splitter here: http://info.sonicretro.org/images/archive/5/5f/20171214123655%21Sonic_1_%28Split_and_Text_by_Hivebrain%29_%28ASM68K%29.zip

If you're savvy enough, you could manually locate and extract the data from your ROM yourself using a hex editor, but the process is too complicated to explain here.
