### ISSUE TITLE
Compatability issues in mapping files

### ISSUE THREAD

**Issue by MDTravisYT** [sonicretro/s1disasm#78]
The recent changes to the files within the _maps folder has caused incompatibility with common editors, such as Flex 2 and SonMapEd. Sure, Flex 2 could be updated to support this, but SonMapEd, an editor plenty still use to this day, will be unable to load these new mappings and DPLC thanks to going out of support years ago. Additionally, if modern editors were updated to support this, it may break compatability with legacy or alternative disassemblies.

**Comment by Clownacy** [comment]
That's why [ClownMapEd](https://forums.sonicretro.org/index.php?threads/clownmaped-the-open-source-sonmaped-clone.41732/) exists - to replicate SonMapEd while supporting things that SonMapEd never did.

Adding support for the newer mappings format would not break compatibility with legacy disassemblies, as support for both are able to co-exist, as they do in ClownMapEd.

**Comment by Clownacy** [comment]
Flex 2 supports the new mappings format as of [version 1.3.0](https://github.com/kirjavascript/Flex2/releases/tag/1.3.0).
